### ISSUE TITLE
LBU question

### ISSUE THREAD

**Issue by gedoensmax** [knoopx/alpine-raspberry-pi#1]
Hi, 
i would like to know if i still have to lbu commit each time i change something or if this is running from the SD card purely and will store changes to the os. 
If i hvae to use `lbu commit` it would be nice if you could tell me how to properly configure it.  
I am not too sure on the whole thing as i only started with alpine running in memory and various docker images but never on an actual Raspberry.

**Comment by knoopx** [comment]
No need to "lbu commit", this project was created just to get rid of that.
