### ISSUE TITLE
default username password for alpine 

### ISSUE THREAD

**Issue by sajjadsabzkar** [knoopx/alpine-raspberry-pi#10]
Hi , i'm try to use username and password 
1. user:root , password:empty
2. user:root , password:root

all of top username and password incorrect to log in to alpine

**Comment by StormYudi** [comment]
Please check the readme.md file:

The image automatically setup and configures:

root user [pwd: raspberry]
pi user [pwd: raspberry]

root / raspberry
pi / raspberry

**Comment by sajjadsabzkar** [comment]
> 



> Please check the readme.md file:
> 
> The image automatically setup and configures:
> 
> root user [pwd: raspberry] pi user [pwd: raspberry]
> 
> root / raspberry pi / raspberry

Thanks
