### ISSUE TITLE
rpi3b+ kernel panic

### ISSUE THREAD

**Issue by vincentserpoul** [knoopx/alpine-raspberry-pi#2]
first, thank you for this repo, I was in the middle of building something similar, but yours seems to fit my needs.
That said, I tried to run it as it is, building on linux, running th runner and burnt the img with etcher: everything went well, except that when I inserted the card in the rpi3b+, it booted and went into kernel panic.

Before I dive into error messages, are you using this repo mostly for rpi4 or are you regularly testing on rpi3 as well?

**Comment by knoopx** [comment]
Hey Vincent, yes, I'm running it on 3b+, 3a+ and 4. Did you try the latest image on the releases page? It might be a recent change, from my experience, they mess kernel/drivers from time to time.

**Comment by vincentserpoul** [comment]
ok, I tried your prebuilt image, it works.
I tried to rebuild the image for aarch64, but it didn't work.
I will look into it :)

**Comment by knoopx** [comment]
I'm not really sure aarch64 is supported at all. If you manage to run it send me a PR ;)

**Comment by vincentserpoul** [comment]
I used to run alpine aarch64 on my rpi3b+ for sure so I guess it should be possible 🤞 .
I'll ofc PR if I manage to do it!

**Comment by vincentserpoul** [comment]
ok, alpine-chroot is supposed to work for many different arch.
I tried rebuilding the rootfs with armhf, it works.
So there must be something else related to aarch64.
Looking into it :)

**Comment by mbl-35** [comment]
Hi @vincentserpoul and @knoopx 
Have the same trouble trying  to create aarch64 image for pi4b (from pi4b, ubuntu server aarch64).
Always got error on alpine-chroot-install (line 330):

```shell
> Downloading` static apk-tools
apk-tools-2.10.4-x86_64-linux.tar.gz: OK
> Installing Alpine Linux latest-stable (aarch64) into chroot
sh: 330: /tmp/tmp.ZHQxrIOCP8/apk: Exec format error
```

Notice that environment variables are not passed to make-image (from docker). Have to specified to the make-image script to be set correctly (beginning make-image: line 3).

```shell
set -xe

export ALPINE_BRANCH=latest-stable
export ALPINE_MIRROR=https://mirrors.ircam.fr/pub/alpine
export ARCH=aarch64

mkdir -p dist /dist
```

I think that I have to also set the apk aarch64 from variable (APK_TOOLS_URI and APK_TOOLS_SHA256) which is set to x86_64. But I don't know what to put here...

I have tried with different FROM in Docker file (FROM arm64v8/ubuntu:18.04) with same results.

@vincentserpoul : Do you have successful build img for aarch64 pi4b?

**Comment by Elevenseas** [comment]
I did not go forward as my initial plan changed a bit (I want to create an automated diskless alpine install) and I will create my own repo.
I'm also working with a rpi3b+ for now, so I can't help you much on the 4b.
By the way, alpine 3.11 now have raspberry-bootloader packages and kernel for rpi4b, so the firmware install should be simplified, but I digress here.

**Comment by mbl-35** [comment]
Thanks for quick reply..
With the aarch64 alpine package downloaded, written to a new formatted Fat32 sdcard, I am not able to boot. (green led blink 4 times, or just multicolor square).
I tried to follow all tuto without success.
Looking again into it !! ;)

**Comment by vincentserpoul** [comment]
> I did not go forward as my initial plan changed a bit (I want to create an automated diskless alpine install) and I will create my own repo.
> I'm also working with a rpi3b+ for now, so I can't help you much on the 4b.
> By the way, alpine 3.11 now have raspberry-bootloader packages and kernel for rpi4b, so the firmware install should be simplified, but I digress here.

It was me, but wrong account logged in, just to be clear :)

**Comment by mbl-35** [comment]
ok, Thanks for your help @vincentserpoul

**Comment by mbl-35** [comment]
Getting aarch64 pi4b with alpine base linux working (so, not using bootstraps script right now).
the pb was the sd card partitionning with gparted or fdisk.
The right way is (found here: https://gitlab.alpinelinux.org/alpine/aports/issues/11342 commented by @macmpi ):

```shell
parted -s $device mktable msdos
parted -s $device unit s -- mkpart primary fat32 2048 526335
parted -s $device unit s -- mkpart primary ext4 526336 -1
parted -s $device -- set 1 boot on
partprobe $device
mkfs.vfat $part
sync
```

**Comment by macmpi** [comment]
Indeed Alpine seems extremely picky on formatting, which is strange, as Raspbian does not seem to care.
In my case, I may have been tricked by my USB-microSD card reader dongle in fact: formatting has been easier with a basic microSD to SD adapter (finally worked with fdisk).

Anyhow, there must be something specific on Alpine kernel image config that defeats bootloader in some (unclear) conditions.

**Comment by hoshsadiq** [comment]
@mbl-35 what does the `$part` variable contain? Do you have a complete example?

**Comment by hoshsadiq** [comment]
@mbl-35, @macmpi what does the `$part` variable contain? Do you have a complete example?
