### ISSUE TITLE
How to enable cgroup?

### ISSUE THREAD

**Issue by beriberikix** [knoopx/alpine-raspberry-pi#3]
I'm trying to use Alpine with [k3s](https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup) with some Pi3+ to save on memory, and I'm new to Alpine. Where can I configure cgroups with this build?

Thanks for doing this!

**Comment by knoopx** [comment]
I know nothing about cgroups but I'm pretty sure they have nothing to do with alpine or anything else related to this repository. That's a kernel feature and you will probably have more luck asking in raspberry pi related forums.

**Comment by beriberikix** [comment]
I think it's a matter of adding a few bits to the `cmdline.txt`. I'll modify `kernel.sh` and report back!

**Comment by beriberikix** [comment]
Yup, [that worked](https://github.com/beriberikix/alpine-raspberry-pi/blob/master/bootstrap/kernel.sh#L5)!

**Comment by knoopx** [comment]
@beriberikix nice to hear you found out how. let me know how k3s works on your pi :)

**Comment by beriberikix** [comment]
It works great! I've been using it for months with a 4GB Pi 4 but now with this Alpine build I can run it on a Pi3 cluster :) Might try to see if I can squeeze out just a bit more RAM somewhere...
