### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by monok-o** [knoopx/alpine-raspberry-pi#4]
Hello !

First know that I'm quit new to alpine and also thank you for this really useful project!
During the build, "apk" can't find the RPI specific packages :
```
fetch https://nl.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch https://nl.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
v3.12.0-463-g5efa865e42 [https://nl.alpinelinux.org/alpine/latest-stable/main]
v3.12.1-5-g0954f48dc3 [https://nl.alpinelinux.org/alpine/latest-stable/community]
OK: 12744 distinct packages available
+ apk add linux-rpi linux-rpi4 raspberrypi-bootloader
ERROR: unsatisfiable constraints:
  linux-rpi (missing):
    required by: world[linux-rpi]
  linux-rpi4 (missing):
    required by: world[linux-rpi4]
  raspberrypi-bootloader (missing):
    required by: world[raspberrypi-bootloader]
```

My issue seem to be simple but I didn't found a lot of solutions...
I tried to change the repositories by those I found in the pre-built image but this didn't changed anything.
Do you know how I could fix this ?

Thank you a lot and have a great day !

**Comment by knoopx** [comment]
These packages are on the official repos, maybe the mirror was broken at the time.

**Comment by monok-o** [comment]
Well, I just cloned the repo again, built the image without modifying anything and the error stay, that's weird...

**Comment by knoopx** [comment]
how are you building the image? under linux or docker?

**Comment by knoopx** [comment]
try overriding the mirror:

```
docker run --privileged --rm -v /dev:/dev:ro -v "$PWD":/runner -w /runner -e ALPINE_BRANCH=latest-stable -e ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine" -e ARCH=aarch64 runner ./make-image
```

**Comment by monok-o** [comment]
I build it under linux (Debian 10), but I already tried to build with docker with the same error.
I just tried your command (before I built the "runner" image), it issued with some errors when installing busybox and some other packages
![image](https://user-images.githubusercontent.com/19715481/98559545-08f3a480-22a7-11eb-9e4f-28d0760fa477.png)

Then I tried to remove some of the environment variable and it seem that specifying the architecture is the cause of this error
But yeah, I can't reach a successful build :/

Also, I tried to change de repositories "edge" but this changed nothing...

**Comment by knoopx** [comment]
armhf is not a supported arch for rpi4, thats why repo doesnt include linux-rpi4
